name: Build and deploy ASP.Net Core app to Azure Web App - medify-api

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'

      - name: Clean
        run: dotnet clean MedifyAPI.sln --configuration Release

      - name: Restore
        run: dotnet restore MedifyAPI.sln

      - name: Publish API
        run: dotnet publish Presentation.Api/Presentation.Api.csproj -c Release -o ./out/publish

      - name: Zip publish folder
        run: |
          cd out/publish
          zip -r ../../app.zip .
          cd ../..

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_CD1653132CC243B9BD1EDDA9C1765455 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_F1989314C84547AE83D77E5402DA365F }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_8DC6F6531F374CCEB9E831DFF16000FB }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'medify-api'
          slot-name: 'Production'
          package: app.zip
